print("   .',;:cc;,'.    .,;::c:,,. ")   
print("   ,ooolcloooo:  'oooooccloo: ")   
print("   .looooc;;:ol  :oc;;:ooooo' ")   
print("     ;oooooo:      ,ooooooc. ")   
print("       .,:;'.       .;:;'. ")       
print("       .... ..'''''. .... ")        
print("     .''.   ..'''''.  ..''. ")     
print("     ..  .....    .....  .. ")      
print("    .  .'''''''  .''''''.  . ")
print("  .'' .''''''''  .'''''''. ''.                          Pi Setup Installer ") 
print("  '''  '''''''    .''''''  ''' ") 
print("  .'    ........... ...    .'. ") 
print("    ....    ''''''''.   .''. ")   
print("    '''''.  ''''''''. .''''' ")   
print("     '''''.  .'''''. .'''''. ")   
print("      ..''.     .    .''.. ")     
print("            .''''''' ")           
print("             ...... ")

